### PR TITLE
Add Generic-derived instances for Serialise

### PR DESCRIPTION
**Pull request by Shimuuar**
This PR is not ready for merge yet and I submit it for feedback. There's no description of encoding format, not enough tests no benchmarks

This implementation doesn't even try to use CBOR maps and uses positional encoding for all data types. Is this OK?

### CODE REVIEW

**Comment by thoughtpolice** [comment]
Thank you for this! I've merged your first two commits after a shuffle, since they're generally useful outside of this and it minimizes the code to review.

/cc @dcoutts - what do you think about the actual encoding, here?

**Comment by dcoutts** [comment]
I have this presentation here that describes the encoding format we want. It is indeed positional, but we always want constructor numbers, even for single constructor types.

http://code.haskell.org/~duncan/binary-ZuriHac-15.pdf

**Comment by Shimuuar** [comment]
OK I'll amend encoding. Should data types isomorphic to () be given special treatments and encoded as null like () does?

Also instances for Maybe and tuples do not follow this pattern. Is this intentional?

**Comment by Shimuuar** [comment]
I've updated  data format for encoding. 

 - How should unit-like data types (like `data Unit = Unit`) be encoded. Same as () to null or as `[0]`
 - How should newtypes be encoded? `encode (T a) ≈ [ 0, encode a ]`?

**Comment by thoughtpolice** [comment]
> - How should unit-like data types (like data Unit = Unit) be encoded. Same as () to null or as [0]

This sounds like a bug IMO: `()` should be encoded as `[0]` IMO, instead of `Null`, precisely because, as @dcoutts said, we always want constructor numbers. This is easily fixable (before release) but we should confirm.

> - How should newtypes be encoded? `encode (T a) ≈ [ 0, encode a ]` ?

This sounds good to me, since the `newtype` itself should have a clearly distinct encoding IMO.

**Comment by Shimuuar** [comment]
Instances for tuples and maybe don't follow this pattern as well:
```
encode (a,b,c) = [encode a, encode b, encode c]

encode Nothing = []
encode (Just a) = [encode a]
```

Is this a bug?

**Comment by thoughtpolice** [comment]
So Duncan and I chatted about this, and basically: these instances aren't technically *consistent* with the API we want users to use. But, these types are also basically 'never going to change', so leaving off tags, etc is mostly just a random choice, because you will not ever have to do any kind of 'schema upgrade' on built in types.

In other words: it's *mostly* an irrelevant detail, even if it's not consistent. The idea with user constructors always using tags is that it gives you a way of doing migrations (even non-automatic ones) between versions of types more easily.

I say *mostly* above because these inconsistencies *do* make certain things more difficult; if, for example, a third-party tool wanted to traverse the CBOR emitted from this library and quasi-interpret the format, constructors, pretty-print the format itself etc, they have to be aware of special cases like `()` being `Null`, which is a bit annoying.

For that reason, I'm probably going to change these instances to be consistent across the board, even if that doesn't ultimately change a whole ton other than some minor things. Better to do this now and be consistent than live with it forever (and repeatedly go back to this point). /cc @dcoutts

**Comment by thoughtpolice** [comment]
This also brings up another point, which is probably that we should have some convenience combinators for doing things like:

```haskell
mkConstr :: Int -> Word -> Encoding
mkConstr len tag = encodeListLen (len+1) <> encodeWord tag
```

which then you could use:

```haskell

instance Serialise a => Serialise (Maybe a) where
  encode Nothing  = mkConstr 0 0             -- zero parameters, tag 0
  encode (Just x) = mkConstr 1 1 <> encode x -- one parameter, tag 1
```

(obviously this is ugly, but just an idea)

**Comment by thoughtpolice** [comment]
Or even better:

```haskell
type Tag = Word

mkConstr :: Tag -> [Encoding] -> Encoding
mkConstr t xs = encodeListLen len <> encodeWord t <> mconcat xs
  where
    len = length xs + 1

instance Serialise a => Serialise (Maybe a) where
  encode Nothing  = mkConstr 0  []
  encode (Just x)   = mkConstr 1 [encode x]
```

**Comment by dcoutts** [comment]
Mm. I'd be tempted to just provide 

    encodeConstructorTag :: Int -> Tag -> Encoding
    encodeConstructorTag size tag = encodeListLen len <> encodeWord tag

because otherwise we have to re-discover the length every time, and do the mconcat.

**Comment by dcoutts** [comment]
@thoughtpolice A generic tool would have to deal with generic CBOR, which includes null etc anyway. Unless the tool somehow knows the schema then I don't see that there's any advantage to trying to make things more uniform when that makes things either bigger or avoids CBOR semantic hints (like using null rather than int 0). If we want to translate into CBOR with more semantic hints for a generic processor then we should use a cbor custom tag to indicate Haskell user-defined sum-of-product constructors.

**Comment by Shimuuar** [comment]
OK now this PR is I think feature complete and have tests. All derived instances follow convention that data types encoded as list with tag as first element and fields.

**Comment by Shimuuar** [comment]
@dcoutts Also what is your opinion on instances for newtype wrappers like `ZipList`, `Data.Monoid.Sum` etc? Should they encode constructor or just serialize underlying data type:

```
instance Serialize a ⇒ Serialize (ZipList a)
  encode (ZipList xs) = encode xs
  decode = ZipList <$> decode
```

**Comment by dcoutts** [comment]
I think the rule must be: decide if they are effectively built-in types that can never possibly change, or if they could ever change representation then they need to be handled like user-defined types.

**Comment by thoughtpolice** [comment]
> I think the rule must be: decide if they are effectively built-in types that can never possibly change, or if they could ever change representation then they need to be handled like user-defined types.

This is kind of what I mean, though. People are terrible at these decisions, like "will that ever change". The set of "Built in types that will never change" may evolve over time, and has the possibility of introducing weird interactions. `()` may not change, but what about `Proxy`, which I believe was only added in GHC 7.8? It has two encodings: `null` or `[0]`. It's not going to change, but let's say someone defines the orphan instance `Serialise a => Serialise (Proxy a)` and they use the 'canonical' encoding `[0]` and then our instance uses `null`. Explosion when they upgrade their compiler. The same could be said of `semigroups` if it gets added to `base`, which we'll clearly have to support instances for soon enough.

It's also a complex rule to explain to the user to avoid this case, and it means we have to update the Generics code to handle more cases like this, I bet, as "fixed types evolve over time". If I'm writing the tutorial, do I dedicate an entire section on "exceptions to the rule of using constructor/list encodings, just in case you think something might not ever change and you want to save 3 bytes"?

When you're already using 1/2 the space of your competitors in the common case, it's not worth shaving off a few bytes with a weird rule like this IMO.

**Comment by Shimuuar** [comment]
I think we have number of different problems mixed up.

1. What data format should generic-derived instances use? I think consensus is it should be array of fields with constructor number as first element. It allows to implement safecopy-like functionality without changes to data format for example.

2. What data format should handwritten instances use. (#15 is probably better place to discuss this). For example we don't need safecopy-like functionality for types in base. Is there common subset of CBOR which all instances should use? Or is it recommendation instead?

One possible advantage is that we don't need to know haskell type of encoded value to do something with it. But then we need to be able to distinguish list which encode ADT and list whihc ancode lists. I'm not sure overhead worth it

@thoughtpolice I think all serializable data types from base should get instance. This will eliminate problem in

**Comment by dcoutts** [comment]
But these are not instances users are writing, it doesn't affect very much, except space and time.

**Comment by dcoutts** [comment]
@Shimuuar if you or @thoughtpolice would like to add a variant to the benchmark using the generic instances, that'd be very useful.

**Comment by Shimuuar** [comment]
I plan to add them but won't be able to start working on it before 20 March.

**Pull request merged**
