### PR TITLE
Add a few benchmarks in bench/Instances

### PR DESCRIPTION
**Pull request by michalt**
This adds benchmarks for serializing and deserializing unboxed
Vectors. In the future we shoud probably include benchmarks for most
(all?) instances defined by the package.

Signed-off-by: Michal Terepeta <michal.terepeta@gmail.com>

### CODE REVIEW

**Comment by thoughtpolice** [comment]
Thanks - I'll get to this shortly. I'm also going to merge this with #42 probably since they sort of overlap.

**Comment by thoughtpolice** [comment]
Sorry about the latency here - I've managed to close #42, but still haven't gotten to incorporating your benchmarks.

Quick braindump: Broadly, I envision the 'instance' tests as tests that *only* ever test CBOR, as they're to be used to make sure you're either improving (or simply not regressing) the instances we provide. That is, the 'instance' category is, broadly speaking, only to back up your theories on if you can speed up the library somehow.

This is essentially what Ben's benchmark did, but yours is more along the lines of the other tests we have - directly comparing performance of an instance *across different packages*. The reason I haven't incorporated your change is because, basically, I'm not exactly sure where to put it yet. But I don't think it should be in the `Instances` namespace.

This is all confused by the fact that the benchmark stanza is rather poorly named now; `vs-other-libs` doesn't entirely describe all the changes I've made (and hope to keep making) to it. It might be better instead to split off the `Instance` namespace into its own executable, that doesn't depend on all the extra machinery for Hackage indexes, etc.

Or just rename the mega-suite to `all-benchmarks` or something. Given the problems with #33 however, I'm inclined to split it off, even if it's more work, so I don't feel like dying every time I try to compile, just for small tests/improvements.

**Comment by dcoutts** [comment]
Mm. Right, I guess it makes sense both to have "cbor-only" benchmarks for catching regressions (or tracking progress) and also the vs-other-libs benchmark that depends on a bunch of other libs, and so is a bit of a pain to build and use (but helpful for making comparisons).

**Comment by thoughtpolice** [comment]
Okay, I finally got around to this! Sorry about that.

**Pull request closed without merging**
