### PR TITLE
Add variant of deserialiseFromBytes returning leftover content

### PR DESCRIPTION
**Pull request by bgamari**
This is useful for things like #78.

### CODE REVIEW

**Comment by bgamari** [comment]
I'm on the fence regarding whether this is an acceptable name. The verbosity of `deserialiseFromBytesWithLeftovers` is quite unfortunate.

**Comment by axman6** [comment]
`deserialiseBytesPartial`? Also, can I make a tiny request that the order of the elements in the returned tuple be reversed to `Either DeserialiseFailure (a,LBS.ByteString)`, which makes writing point free code a little nicer.

**Comment by bgamari** [comment]
I'm a bit surprised that the you want the tuple reversed. Afteall, the "functorial" argument of `(,)` is the second argument. I would think that you would want the current `(ByteString, a)` ordering as then you can easily map over the result.

**Comment by dcoutts** [comment]
It's a long name to start with. I'd be tempted to make this the main version rather than a variant. If we need a convenience function then it could do with a shorter name anyway.

**Comment by axman6** [comment]
@bgamari hmm, good point.

**Pull request merged**
