### PR TITLE
Write: improve Integer serialisation for GMP

### PR DESCRIPTION
**Pull request by michalt**
This rewrites serialization to use `exportIntegerToAddr` as suggested by @dcoutts (code is simpler and it's faster: ~19us vs ~12us).

@dcoutts Let me know if this is what you had in mind - I'm not that familiar with the `ByteString` internals (i.e., I hope I'm not doing something silly here).

### CODE REVIEW

**Comment by dcoutts** [comment]
@michalt Yes this is great. In principle we can probably go slightly better if we take advantage of the `Integer` representation and drop down to the `BigNat`s. That'd help the negative case as we would not have to do the `(-1-n)` conversion.

BTW, It looks like the `Integer` benchmark currently does not covers negative integers. It's probably worth adding those as separate cases. That'll let us see any improvement we might make here.

So look at code in `toBuilder` in the `#if defined(OPTIMIZE_GMP)` case. We case on the Integer rep. Now I it is [an invariant of the `Integer` type that it's always in its most reduced form](https://hackage.haskell.org/package/integer-gmp-1.0.0.0/docs/GHC-Integer-GMP-Internals.html#t:Integer), so we don't actually need to do those small int tests in the `Gmp.Jp#`/`Gmp.Jn#` cases. But even better, we now know the sign of the big integer, and we have access to the `BigNat` inside the `Gmp.Jp#` `Gmp.Jn#` constructors.

So the something like (untested)
```
              -- This code is specialized for GMP implementation of Integer. By
              -- looking directly at the constructors we can avoid some checks.
              -- S# hold an Int, so we can just use intMP.
              TkInteger (Gmp.S# i) vs' -> PI.runB intMP (I# i) op >>= go vs'
              -- Jp# is for > 0.
              TkInteger (Gmp.Jp# n) vs' ->
                BI.runBuilderWith
                  (bigNatMP n) (step vs' k) (BI.BufferRange op ope0)
              -- Jn# is for < 0.
              TkInteger (Gmp.Jn# n) vs' -> 
                BI.runBuilderWith
                  (negBigNatMP x) (step vs' k) (BI.BufferRange op ope0)
```

So instead of `integerMP` this uses a `bigNatMP` and `negBigNatMP` like:
```
bigNatMP :: Gmp.BigNat -> B.Builder
bigNatMP n = P.primBounded header 0xc2 <> bigNatToBuilder n

negBigNatMP :: Gmp.BigNat -> B.Builder
negBigNatMP n = P.primBounded header 0xc3 <> bigNatToBuilder n
```

Then this `bigNatToBuilder` is  essentially identical to your `integerToBuilder` except that calls the `BigNat` versions of those size & export primitives instead of the `Integer` variants. Yes, I think your `integerToBuilder` is using the `Builder` primitives in the right way.

It's also worth noting that the GMP representation changed in 7.10 (and the export primitives were added). Prior to this we can only do the small int vs big int, and will have to have either generic or perhaps something like your original export code for that case (the code that walked the limbs directly).

**Comment by michalt** [comment]
Cool, thanks for comments! Good idea with the benchmarks - I'll send a PR for adding something for negative `Integer`s first.

I'm not sure we'll be able to go as far as you're suggesting though. For instance, `Integer` is normalized, but it starts using `Jp#` and `Jn#` as soon as things don't fit in `Int#`, but here the condition is whether things fit into a `Word`, right? (e.g., we're using `word64MP`). Also `negBigNatMP` will probably need to subtract 1 from the value (since CBOR stores is `-1 - n` for negative values).

**Comment by michalt** [comment]
@dcoutts I've rebased and updated the commit with your ideas. A few things to note:

- We still do comparison with the `maxBound` of `Word` (since `integer-gmp` is only checking for things to fit in an `Int`).
- `negBigNatMP` subtracts 1 from the `BigNat` (due to CBOR requiring `-1 - n` for the negative case).
- `integerMP` is only used for the no-GMP case (we use `bigNatMP` and `negBigNatMP` for GMP).

This brings the runtime in the benchmark down to ~10us for the positive `Integer`s (haven't yet checked the negative ones).

**Comment by dcoutts** [comment]
@michalt those are good points re Int vs Word, and the -1. I concur.

Ok, this looks great. Interested to see the negative benchmarks.

@thoughtpolice I'm happy if you are.

**Comment by michalt** [comment]
@dcoutts The benchmarks are nice :-)
Generic version (not specialized for GMP):
```
benchmarking integer/serialise/large positive
time                 74.42 μs   (74.25 μs .. 74.57 μs)
                     1.000 R²   (0.999 R² .. 1.000 R²)
mean                 75.04 μs   (74.78 μs .. 75.69 μs)
std dev              1.315 μs   (583.9 ns .. 2.229 μs)
variance introduced by outliers: 12% (moderately inflated)

benchmarking integer/serialise/large negative
time                 74.98 μs   (74.83 μs .. 75.09 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 75.46 μs   (75.43 μs .. 75.50 μs)
std dev              111.3 ns   (89.43 ns .. 139.1 ns)
```
GMP version before this PR:
```
benchmarking integer/serialise/large positive
time                 19.83 μs   (19.75 μs .. 19.97 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 19.77 μs   (19.75 μs .. 19.84 μs)
std dev              107.8 ns   (9.310 ns .. 227.1 ns)

benchmarking integer/serialise/large negative
time                 21.82 μs   (21.81 μs .. 21.82 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 21.81 μs   (21.81 μs .. 21.82 μs)
std dev              11.21 ns   (9.090 ns .. 13.96 ns)
```
HEAD:
```
benchmarking integer/serialise/large positive
time                 10.93 μs   (10.93 μs .. 10.93 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 10.93 μs   (10.93 μs .. 10.93 μs)
std dev              2.228 ns   (1.454 ns .. 4.428 ns)

benchmarking integer/serialise/large negative
time                 11.74 μs   (11.74 μs .. 11.74 μs)
                     1.000 R²   (1.000 R² .. 1.000 R²)
mean                 11.74 μs   (11.74 μs .. 11.75 μs)
std dev              2.673 ns   (2.166 ns .. 3.700 ns)
```

**Pull request merged**
